### ISSUE TITLE
Mochiweb performance issue.

### ISSUE THREAD

**Issue by huang1196** [mochi/mochiweb#130]
It seems that mochiweb had same performance issue. The longest request time is much more than the mean time. Why that happens?

1. make app PROJECT=bch
2. add a new path:

    case Path of  "home" ->
          Req:ok({"text/javascript", "Hello!"});
      _ ->
           Req:serve_file(Path, DocRoot)
     end;

3. run the app on port 80 with parameters "+K true +P 1000000"

4.  ab -n 100000 -c 800 192.168.1.2/home

Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests

Server Software:        MochiWeb/1.0
Server Hostname:        192.168.1.2
Server Port:            80

Document Path:          /home
Document Length:        3 bytes

Concurrency Level:      800
Time taken for tests:   10.587 seconds
Complete requests:      100000
Failed requests:        0
Write errors:           0
Total transferred:      16446576 bytes
HTML transferred:       300852 bytes
Requests per second:    9445.95 [#/sec] (mean)
Time per request:       84.692 [ms] (mean)
Time per request:       0.106 [ms] (mean, across all concurrent requests)
Transfer rate:          1517.12 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0   48 139.6     31    3042
Processing:     6   36  14.9     37     375
Waiting:        3   27  13.6     28     368
Total:          9   83 141.6     69    3090

Percentage of the requests served within a certain time (ms)
  50%     69
  66%     75
  75%     77
  80%     79
  90%     84
  95%     90
  98%    371
  99%   1065
 100%   3090 (longest request)

5. cat /etc/sysctl.conf

net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
kernel.printk = 8 4 1 7
kernel.printk_ratelimit_burst = 10
kernel.printk_ratelimit = 5

net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_mem = 50576 64768 98152
net.core.netdev_max_backlog = 2048
net.core.somaxconn = 1024
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1

**Comment by etrepum** [comment]
I'm going to close this as it seems to be an OS related issue, perhaps related to EC2's virtualization. Not sure if there's anything mochiweb can do to mitigate this.
