### ISSUE TITLE
how is used acceptor_pool_size with max

### ISSUE THREAD

**Issue by benoitc** [mochi/mochiweb#143]
Hi,

I am not sure to understand the difference between acceptor_pool_size and max. What is the purpose of this maximum here ?

**Comment by etrepum** [comment]
The acceptor pool is kept at a constant size, when a connection is accepted a new acceptor is created. The max controls the maximum amount of requests being handled concurrently.

**Comment by benoitc** [comment]
thanks for the answrer!
