### ISSUE TITLE
confusing to the activesockets 

### ISSUE THREAD

**Issue by forkbomb-mj** [mochi/mochiweb#149]
Hello, I feel confusing. In the line 329 to the mochiweb_socket_server.erl.
I change the max to 20 in the state that named mochiweb_socket_server, and connect max users then close connections, and I do it several times. I found that the activesockets will increase the value of acceptor_pool_size(the value is 16), it lead to the next time can only connect 16 users and others are in the backlog because of the activessockets record a incorrect value. 

It just likes this table :
![cut](https://cloud.githubusercontent.com/assets/5810061/5892697/6313cfee-a503-11e4-9f2b-54a203ad4f28.jpg)
in the second time,  the last four user cann't come in.

Thanks for your help :-)

**Comment by etrepum** [comment]
Please try the branch active-socket-149 and let me know if this problem persists. I haven't had a chance to come up with a test suite for the issue, but the code is much cleaner and I expect it to work now.

**Comment by etrepum** [comment]
https://github.com/mochi/mochiweb/commit/63947f4a23010e0c7c810a23e01ac681c14b9f1e

**Comment by forkbomb-mj** [comment]
:+1: this problem has disappeared in the new code.

**Comment by etrepum** [comment]
Fixed by #150
