### ISSUE TITLE
truncated post body received by mochiweb

### ISSUE THREAD

**Issue by leiyangyou** [mochi/mochiweb#151]
Hi there,

We are having an issue with mochiweb truncating a large POST body (specically JSON data).

Has anyone else experience the same problem?

Mochiweb version: 2.3

**Comment by etrepum** [comment]
Do you have a reproducible example of this? What are the headers and how truncated is it? How are you reading the body?

**Comment by leiyangyou** [comment]
Sorry Bob @etrepum,

Missed your message last time.

It's a long piece of JSON data, and we are using Req:recv_body()

**Comment by mworrell** [comment]
@leiyangyou In `mochiweb_request` there is a default for the maximum body length to be received:

```Erlang
% Maximum recv_body() length of 1MB
-define(MAX_RECV_BODY, (1024*1024)).
```

If you want to receive more, try using `recv_body/2` instead:

```Erlang
%% @spec recv_body(integer(), request()) -> binary()
%% @doc Receive the body of the HTTP request (defined by Content-Length).
%%      Will receive up to MaxBody bytes.
recv_body(MaxBody, {?MODULE, [_Socket, _Method, _RawPath, _Version, _Headers]}=THIS) ->
```

**Comment by etrepum** [comment]
This is a defense against a denial of service attack, since all of the data is read synchronously into a single binary it's possible to exhaust all RAM if this call is unbounded. If you are expecting a very large request body you should figure out how to process it in a streaming fashion (e.g. using `stream_body/4`).

**Comment by mworrell** [comment]
Indeed, don't accept in-memory date larger than a couple of MB, unless you have checked the sender.
