### ISSUE TITLE
Allow no recbuf on socket

### ISSUE THREAD

**Issue by jgrnt** [mochi/mochiweb#153]
Hi,

I would to integrate the idea initially proposed in #134, where also no *recbuf* option can be supplied to the gen_tcp socket.
I was investigating discoproject/disco#603 under Linux and figured out that when an explicit RCVBUF is set on the socket under linux, this limits the maximum TCP window, which leads on a high latency link (200ms RTT) to very poor performance (few kb/s)
(Details about the window sizing in linux can be found in http://www.psc.edu/index.php/networking/641-tcp-tune#Linux)

So when i removed *recbuf* I got comparable performance to a low-latency link.
In order do not break backwards compatibility I propose as in #134 to set the *recbuf* option to *undefined* to override the default.

**Comment by etrepum** [comment]
Sounds reasonable, go ahead and send a PR.
