### ISSUE TITLE
travis does not seem to run - enable travis for repo

### ISSUE THREAD

**Issue by robertkowalski** [mochi/mochiweb#160]
I just wanted to send a PR as it looked to me that travis was not set up for the repo as my PRs are not tested. 

I noticed that there is already a travis.yml but the testing does not seem to be enabled on the travis side.

Can you enable it? I think #2 from this getting started is missing:

http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by etrepum** [comment]
It's definitely enabled, and has run in the past. If it's not running then it's an issue on Travis's side that I don't have any control over. https://travis-ci.org/mochi/mochiweb

**Comment by etrepum** [comment]
I just went into settings and flipped a switch somewhere that they must've turned off on their end at some point. Might work now on next push.

**Comment by robertkowalski** [comment]
thank you :)
