### ISSUE TITLE
Headers ordering

### ISSUE THREAD

**Issue by eLRuLL** [mochi/mochiweb#162]
In some cases headers order matter, like [here](http://stackoverflow.com/questions/750330/does-the-order-of-headers-in-an-http-response-ever-matter)

Could this be changed somehow? and why is it important to handle headers on a `gb_tree` structure?

**Comment by etrepum** [comment]
The gb_tree data structure is necessary for performance reasons. What's your use case? When multiple headers with the same name are present, they are combined in the order that they were received.

```
`> mochiweb_headers:to_list(mochiweb_headers:make([{"foo", "a"}, {"foo", "b"}])).
[{"foo","a, b"}]
```

**Comment by eLRuLL** [comment]
I am using mochiweb like a proxy, so I need to pass a server response to the client and the server response headers are like:

    Set-Cookie: selectedCountry=US; Expires=Sat, 29 Aug 2015 15:16:49 GMT; Path=/; Domain=.example.com
    Set-Cookie: selectedCountry=GB; Expires=Sat, 29 Aug 2015 15:16:49 GMT; Path=/; Domain=.example.com

but when passing through mochiweb, it returns:

    Set-Cookie: selectedCountry=GB; Expires=Sat, 29 Aug 2015 15:16:49 GMT; Path=/; Domain=.example.com
    Set-Cookie: selectedCountry=US; Expires=Sat, 29 Aug 2015 15:16:49 GMT; Path=/; Domain=.example.com

Which sets incorrect cookie on the client side.

**Comment by etrepum** [comment]
Order for Set-Cookie is preserved. Are you doing some sort of transformation? How exactly are you generating the headers for the response?

```erlang
1> mochiweb_headers:to_list(mochiweb_headers:make([{"Set-Cookie", "selectedCountry=GB"}, {"Set-Cookie", "selectedCountry=US"}])).
[{"Set-Cookie","selectedCountry=GB"},
 {"Set-Cookie","selectedCountry=US"}]
```

This ordering property is tested (in a few places, here's one):

```erlang
set_cookie_test() ->
    H = make([{"set-cookie", foo}, {"set-cookie", bar}, {"set-cookie", baz}]),
    ?assertEqual(
       [{"set-cookie", "foo"}, {"set-cookie", "bar"}, {"set-cookie", "baz"}],
       to_list(H)),
    ok.
```

**Comment by etrepum** [comment]
Ok, I found the issue, it's with formatting the headers in the response, not with mochiweb_headers itself.

**Comment by eLRuLL** [comment]
thanks for this :+1:
