### ISSUE TITLE
mochiutf8 `codepoint_to_bytes` failing for values between 55296 and 57343

### ISSUE THREAD

**Issue by jockee** [mochi/mochiweb#164]
:mochiweb_html.parse("&#55357;&#56842;")
    ** (FunctionClauseError) no function clause matching in :mochiutf8.codepoint_to_bytes/1
      src/mochiutf8.erl:38: :mochiutf8.codepoint_to_bytes(55357)
      src/mochiweb_html.erl:665: :mochiweb_html.tokenize_charref/3
      src/mochiweb_html.erl:642: :mochiweb_html.tokenize_charref/2
      src/mochiweb_html.erl:302: :mochiweb_html.tokens/3
      src/mochiweb_html.erl:82: :mochiweb_html.parse/1

Bumped into this when trying to parse HTML containing `&#55357;&#56842;`, which looks like it's supposed to represent the "😊" smiley.

http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%98%8A - under surrogates.

**Comment by etrepum** [comment]
While this is a bug (can't handle surrogates as charrefs), it wouldn't work if that bug was fixed because it can't handle parsing anything without a surrounding tag.

**Comment by etrepum** [comment]
Fixed in 2.13.0

**Comment by jockee** [comment]
Great stuff! Thanks!
