### ISSUE TITLE
question about mochiglobal

### ISSUE THREAD

**Issue by WanliTian** [mochi/mochiweb#170]
if i have one process to update values maintained by mochiglobal for every one minute, and hundreds of processes to access these value with mochiglobal. Is it save to these reading processes?

**Comment by etrepum** [comment]
I am not sure what you mean exactly, but the use case for mochiglobal is to share infrequently updated data across processes. Once a minute is probably not a bottleneck, but there is some synchronization in Erlang code loading so you should always profile to make sure that the variance is acceptable during that reloading window. If the data is not large, ets may be a better solution.
