### ISSUE TITLE
publish package in hex.pm

### ISSUE THREAD

**Issue by benoitc** [mochi/mochiweb#175]
Would be cool if you can publish the latest version in hex.pm

**Comment by etrepum** [comment]
I've never used hex.pm before, do you want to do it?

**Comment by benoitc** [comment]
ok will do tomorrow. thanks!

**Comment by philss** [comment]
Hey guys, I published [the package](https://hex.pm/packages/mochiweb/2.12.2) using the deprecated [community packages](https://github.com/hexpm/community). I'm not sure if you will be able to publish a newer version of the package. Please let me know if you have any trouble.

**Comment by benoitc** [comment]
@philss will need to send an email :)

@etrepum pr on its way, have been distracted, sorry for that...

**Comment by benoitc** [comment]
fixed in 1dd0e6aee0cebe93b371d476fbeb590e40ccbb2f . I will keep the issue open until the project hasn't been put in hex.pm

**Comment by philss** [comment]
@benoitc ok, thanks! I sent the email requesting ownership for the package. After that I will transfer or add you both as owners.

**Comment by benoitc** [comment]
Philip i alreay contact them :) Hopefully it will be done by monday. Anyway
thanks :)

**Comment by benoitc** [comment]
@etrepum @philss done the package is now updated in hex.pm :)
https://hex.pm/packages/mochiweb

**Comment by philss** [comment]
@benoitc @etrepum great! :)

One more thing: I'm currently maintaining the `mochiweb_html` [package](https://hex.pm/packages/mochiweb_html) which is a [fork](https://github.com/philss/mochiweb_html) with only the HTML parser extracted from Mochiweb. Please let me know if you see something wrong with that.
