### ISSUE TITLE
acceptor_error

### ISSUE THREAD

**Issue by fbeline** [mochi/mochiweb#185]
Hi recently I was doing some stress tests in my project that uses mochiweb, and when I test it in my local machine with 20k requests by second I started to get the following error:
{mochiweb_socket_server,341,{acceptor_error,{error,accept_failed}}}

What exactly it means? Can I configure it somehow to improve the amount of requests/second ?

Thanks

**Comment by etrepum** [comment]
This is likely a platform specific kernel/sysctl tuning problem, but you haven't specified which platform you have done this testing with, or with which tools.

**Comment by FelipeBB** [comment]
The plataform is a ubuntu 16.04, and the tool used to do the tests is [vegeta](https://github.com/tsenart/vegeta).
