### ISSUE TITLE
Please publish 2.17 to Hex.pm

### ISSUE THREAD

**Issue by dkarter** [mochi/mochiweb#194]
Hey @benoitc I was looking at https://hex.pm/packages/mochiweb and it says you are the owner. I'm not sure how this mechanism works on Hex to push out a new version of an Erlang package, but the latest mochiweb release is v2.17 and on Hex it is v2.15.

I'd love to help any way I can.

Thanks!

**Comment by etrepum** [comment]
It would be great if there was a way to get this to just happen with a travis script of some kind based on the tag!

**Comment by mworrell** [comment]
That is actually what we are doing in our libraries.
The moment we push a tag on the master we also publish automatically to Hex.

https://github.com/zotonic/z_stdlib

Check `hex.sh` and `.travis.yml`

**Comment by benoitc** [comment]
2.18 is on hex now. Sorry for the delay. maybe we could indeed make it automatic... if anyone wants to make a PR?
