### ISSUE TITLE
Strict-SSL

### ISSUE THREAD

**Issue by alawatta** [mochi/mochiweb#207]
Hi,
How to enable strict-ssl in mochiweb ?
Br,
Shehan Robert

**Comment by etrepum** [comment]
Could you be a little more clear about what you mean by "strict-ssl"?

**Comment by alawatta** [comment]
Tx for quick response.
We establish web service, based on mochi-web. (SSL enable) when we check our site using below URL, it shows some errors.
https://www.sslshopper.com/ssl-checker.html
here attached screen shot of above validation output.

![ssl_checker_output](https://user-images.githubusercontent.com/10415847/49412491-93b1f780-f792-11e8-90b0-58b9a0899498.jpg)

Reference:
https://blog.cloudflare.com/introducing-strict-ssl-protecting-against-a-man-in-the-middle-attack-on-origin-traffic/

**Comment by etrepum** [comment]
Looks like you need to follow the instructions and include the intermediate certificate, normally this is done by concatenating your public key and the intermediate certificate’s public key and configuring the application to use that file. I don’t recall which is supposed to go first (or if that matters) but I’m sure if you follow cloudflare’s links they’ll have more information.

**Comment by alawatta** [comment]
Tx a lot for help & let you know the status ..

**Comment by alawatta** [comment]
it is resolved after adding following option. Tx for help..
{cacertfile, PemFile} to Option List in mochiweb_http:start.

ex:
Options = [{ip, Ip},{port, Port},{ssl, true}, {ssl_opts, [{certfile, CertFile},{keyfile, KeyFile},{cacertfile, PemFile}]}]
