### ISSUE TITLE
Warning On OTP 21.2

### ISSUE THREAD

**Issue by suexcxine** [mochi/mochiweb#209]
===> Compiling mochiweb
_build/default/lib/mochiweb/src/mochiweb_socket.erl:91: Warning: ssl:ssl_accept/2: deprecated; use ssl:handshake/2 instead

**Comment by OvermindDL1** [comment]
Still the same warning on the latest published version of 2.18.0 on OTP 21.2.2.

**Comment by OvermindDL1** [comment]
Well that was quite a bug waiting to happen there, good to see it'll be fixed in the next OTP release!  ^.^;

Thanks for the update!

**Comment by etrepum** [comment]
21.2.3 is released (at least in the form of a tag on github) but I'm going to hold back a mochiweb release until it's available to use from travis-ci.

**Comment by OvermindDL1** [comment]
> 21.2.3 is released (at least in the form of a tag on github) but I'm going to hold back a mochiweb release until it's available to use from travis-ci.

Looking forward, thanks much!!
