### ISSUE TITLE
ssl issue, how to fix?

### ISSUE THREAD

**Issue by xerosanyam** [mochi/mochiweb#216]
line 131 in context connection_crashed
11:09:13.673 [error] Error in process <0.1760.0> on node '829568ba27fb@172.17.0.2' with exit value:
{{ssl_error,{options,{certfile,"/etc/letsencrypt/live/<domain>/fullchain.pem",{error,enoent}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
11:09:13.674 [error] Supervisor 'esockd_connection_sup - <0.1590.0>' had child connection started with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.1760.0> exit with reason {ssl_error,{options,{certfile,"/etc/letsencrypt/live/<domain>/fullchain.pem",{error,enoent}}}} in esockd_connection:upgrade/1 line 131 in context connection_crashed

**Comment by etrepum** [comment]
`{error, enoent}` means the file doesn’t exist. It looks like you have two slashes in the path for your fullchain.pem certificate which might be the issue.
