### ISSUE TITLE
Documentation for setting up the project

### ISSUE THREAD

**Issue by kbajno** [mochi/mochiweb#217]
I noticed that there is a lack of documentation that is easy to find for setting up the project. This can make it difficult for newcomers who want to contribute to the project to be able to do so. In the readme I noticed there was a command to run for the project, but no further information. I think it would be helpful if there were some clear headings on what the information is. Also, if the information exists somewhere already it would be beneficial to include it there.

**Comment by etrepum** [comment]
Is there a reason you're interested in using mochiweb instead of cowboy or Yaws?
