### ISSUE TITLE
mochiweb seems to be incompatible with otp 25

### ISSUE THREAD

**Issue by elsbiet** [mochi/mochiweb#250]
just tried to start a new webmachine project using otp 25.

executing rebar3 compile for the fresh created skeleton (rebar3 new webmachine test) gives the follwing errors: 

 _build/default/lib/mochiweb/src/mochiweb_session.erl:145:13: Warning: crypto:block_encrypt/4 is removed; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:150:5: Warning: crypto:block_decrypt/4 is removed; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:154:5: Warning: crypto:hmac/3 is removed; use crypto:mac/4 instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:158:5: Warning: crypto:hmac/3 is removed; use crypto:mac/4 instead

_build/default/lib/mochiweb/src/mochiweb_socket.erl:33:45: Warning: ssl:cipher_suites/0 is removed; use cipher_suites/2,3 instead

will this be fixed?

thanks for your answer, e.

**Comment by etrepum** [comment]
This is an issue with webmachine depending on an old version of mochiweb (Version 2.20.0 released 2019-07-14). Current releases are compatible.

https://github.com/webmachine/webmachine/blob/master/rebar.lock
https://github.com/mochi/mochiweb/commit/cedc22f66a8e3f3885fb06babc0c0582418508f8

**Comment by elsbiet** [comment]
thanks
